services:
  - type: web
    name: backend-boletos-v2
    env: node
    buildCommand: npm install && npm run install-chrome
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: RENDER
        value: true
