services:
  - type: web
    name: backend-boletos-v2
    env: node
    buildCommand: |
      npm config set registry https://registry.npmjs.org/
      npm ci --only=production --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
